### PR TITLE
Added Andy Code

### PR DESCRIPTION
**Pull request by andyeggs**

### CODE REVIEW

**Comment by SharazFERG** [comment]
i feel like this is offensive to someone

**Comment by andyeggs** [comment]
dopeahole

**Comment by SharazFERG** [comment]
that is very racist how do you sleep at night

**Comment by andyeggs** [comment]
poison

**Comment by SharazFERG** [comment]
[http://media3.giphy.com/media/kEKcOWl8RMLde/giphy.gif](url)

**Pull request merged**
